### ISSUE TITLE
Impossible to bind smtp on port 25

### ISSUE THREAD

**Issue by fliespl** [andrelohmann/ansible-role-mailpit#6]
Aug 26 08:44:06 flies-PC mailpit[1745734]: time="2024/08/26 08:44:06" level=fatal msg="listen tcp 0.0.0.0:25: bind: permission denied"

I think some changes to unit are required.

Extended import_task with another one:

```
- name: Add cap_net_bind_service to /usr/local/bin/mailpit
  community.general.capabilities:
    path: /usr/local/bin/mailpit
    capability: cap_net_bind_service+ep
    state: present
```
